[package]
name = "ray-tracer-challenge"
version = "0.1.0"
authors = ["Jason Duffy <jasonsduffy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.8.0"
num-traits = "0.2.14"
